org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1
minecraft_version_range=[26.1,)
neo_version=26.1.0.18-beta
neo_version_range=[26.1.0.0-beta,)

mod_id=showcaseitem
mod_name=Showcase Item
mod_url=https://www.curseforge.com/minecraft/mc-mods/showcase-item
mod_license=Attribution-NonCommercial-ShareAlike 3.0 Unported
mod_issue_tracker=https://github.com/starforcraft/Showcase-Item/issues/new/choose
mod_version=26.1-2.0.3
currentChangelog=- Fixed incorrect [PlayerName] shared an item message
mod_group_id=com.ultramega.showcaseitem
mod_authors=Ultramega
mod_description=This mod allows to showcase items in the chat.
