modLoader="javafml"
loaderVersion="[43,)"
license="Attribution-NonCommercial-ShareAlike 3.0 Unported"
issueTrackerURL="https://github.com/starforcraft/Showcase-Item/issues/new/choose"
[[mods]]
modId="showcaseitem"
version="${file.jarVersion}"
displayName="Showcase Item"
displayURL="https://www.curseforge.com/minecraft/mc-mods/showcase-item"
logoFile="logo.png"
credits="Thanks for downloading this mod."
authors="Ultramega"
description="This mod allows to showcase items in the chat"

[[dependencies.showcaseitem]]
modId="forge"
mandatory=true
versionRange="[43.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.showcaseitem]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"